librariapp/config/routes.rb
Rails.application.routes.draw do
  resources :clients

  resources :promotions

  resources :order_details

  resources :orders

  resources :sale_details

  resources :sales

  resources :customers

  resources :products

  resources :categories

  resources :providers

end

librariapp/app/views/promotions/_form.html.erb
<%= form_for @promotion, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombreCliente, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombreCliente, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fecha, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vendedor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vendedor, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :medioComunicacion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :medioComunicacion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :promocion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :promocion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :acuerdos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :acuerdos, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                promotions_path, :class => 'btn' %>
  </div>
<% end %>

librariapp/app/views/promotions/edit.html.erb
<%- model_class = Promotion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

librariapp/app/views/promotions/index.html.erb
<%- model_class = Promotion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombreCliente) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:vendedor) %></th>
      <th><%= model_class.human_attribute_name(:medioComunicacion) %></th>
      <th><%= model_class.human_attribute_name(:promocion) %></th>
      <th><%= model_class.human_attribute_name(:acuerdos) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= link_to promotion.id, promotion_path(promotion) %></td>
        <td><%= promotion.nombreCliente %></td>
        <td><%= promotion.fecha %></td>
        <td><%= promotion.vendedor %></td>
        <td><%= promotion.medioComunicacion %></td>
        <td><%= promotion.promocion %></td>
        <td><%= promotion.acuerdos %></td>
        <td><%=l promotion.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_promotion_path(promotion), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      promotion_path(promotion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_promotion_path,
            :class => 'btn btn-primary' %>

librariapp/app/views/promotions/new.html.erb
<%- model_class = Promotion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

librariapp/app/views/promotions/show.html.erb
<%- model_class = Promotion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombreCliente) %>:</strong></dt>
  <dd><%= @promotion.nombreCliente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @promotion.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vendedor) %>:</strong></dt>
  <dd><%= @promotion.vendedor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medioComunicacion) %>:</strong></dt>
  <dd><%= @promotion.medioComunicacion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:promocion) %>:</strong></dt>
  <dd><%= @promotion.promocion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:acuerdos) %>:</strong></dt>
  <dd><%= @promotion.acuerdos %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              promotions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_promotion_path(@promotion), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              promotion_path(@promotion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>