librariapp/config/routes.rb
Rails.application.routes.draw do
  resources :clients

  resources :promotions

  resources :order_details

  resources :orders

  resources :sale_details

  resources :sales

  resources :customers

  resources :products

  resources :categories

  resources :providers

end

librariapp/app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :sales

	#validates :nombre, :email, :presence => { message: "No puede dejarse vacío" }
end

librariapp/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    
    if params[:q]
      @customers = Customer.where("nombre  LIKE '%"+params[:q]+"%'")
    else
      @customers = Customer.all
    end
    #@clients = Client.all
    #@clients = Client.find(:all,:conditions => ['nombre LIKE ?', "#{params[:q]}%"],  :limit => 8, :order => 'nombre')
    respond_to do |format|
      format.html
      format.json { render :json => @clients }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.valid? 
        puts "cliente valido"
        if @customer.save
          format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
          format.json { render :show, status: :created, location: @customer }
        else
          format.html { render :new }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find
    respond_to do |format|
      if params[:id]
        @client = Customer.find_by id: params[:id]
      end
      if @customer.nil?
        @customer = Customer.new
        format.html { render :new }
      else
        format.html { render :show }
      end
      format.json { render json: @client, status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:nombreCliente, :telefono, :direccion, :RFC, :correo, :facebook, :linkedln)
    end
end

librariapp/app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombreCliente, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombreCliente, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :telefono, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefono, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :RFC, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :RFC, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :correo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :correo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :facebook, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :facebook, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :linkedln, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :linkedln, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

librariapp/app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

librariapp/app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombreCliente) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:RFC) %></th>
      <th><%= model_class.human_attribute_name(:correo) %></th>
      <th><%= model_class.human_attribute_name(:facebook) %></th>
      <th><%= model_class.human_attribute_name(:linkedln) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.nombreCliente %></td>
        <td><%= customer.telefono %></td>
        <td><%= customer.direccion %></td>
        <td><%= customer.RFC %></td>
        <td><%= customer.correo %></td>
        <td><%= customer.facebook %></td>
        <td><%= customer.linkedln %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

librariapp/app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

librariapp/app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombreCliente) %>:</strong></dt>
  <dd><%= @customer.nombreCliente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @customer.telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @customer.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:RFC) %>:</strong></dt>
  <dd><%= @customer.RFC %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correo) %>:</strong></dt>
  <dd><%= @customer.correo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= @customer.facebook %></dd>
  <dt><strong><%= model_class.human_attribute_name(:linkedln) %>:</strong></dt>
  <dd><%= @customer.linkedln %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>