config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients

  resources :promotions

  resources :order_details

  resources :orders

  resources :sale_details

  resources :sales

  resources :customers

  resources :products

  resources :categories

  resources :providers

  root 'sales#index'

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :customer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fecha, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :importe, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :importe, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:importe) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.customer_id %></td>
        <td><%= sale.fecha %></td>
        <td><%= sale.importe %></td>
        <td><%=l sale.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @sale.customer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @sale.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:importe) %>:</strong></dt>
  <dd><%= @sale.importe %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>